### ISSUE TITLE
Is there a plan to streamline versions?

### ISSUE THREAD

**Issue by chrkaatz** [mren/pgmigrate#11]
NPM has a version 2.1.0 (https://www.npmjs.com/package/megrim) here it is 1.2.0...

**Comment by mren** [comment]
Hey :)

I renamed the project from megrim to pgmigrate.

The last version of megrim is 2.1.0.
After megrim 2.1.0 is pgmigrate 1.0.0.
The latest version of pgmigrate is 1.2.0 and is published to github.

Sorry for the confusion. In hindsight it would have been better to give pgmigrate a higher version number than the latest megrim version number.
